logfile = { ...
    'panel-0521/log-sensor.txt', ...
    'panel-0524/log-sensor.txt', ...
    'panel-0531/log-sensor.txt', ...
    'panel-0607/log-sensor.txt', ...
    };
[f, stat_all] = recv_event_stat_core(logfile);

print(f, ['testbed-result/real.eps'], '-depsc');
